apiVersion: v1
kind: PersistentVolume
metadata:
  name: redmine-0
  labels:
    app.kubernetes.io/instance: redmine
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  local:
    path: /mnt/common/tmp/k8s/redmine-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s01
