apiVersion: v1
kind: PersistentVolume
metadata:
  name: wiki
  labels:
    app: dokuwiki
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  local:
    path: /mnt/common/tmp/k8s/wiki-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s01
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wiki
  labels:
    name: wiki
spec:
  ingressClassName: nginx
  rules:
  - host: findip.nif.catchmedia.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: wiki-dokuwiki
            port: 
              number: 80
